// <auto-generated />
using System;
using MezunBilgiSistemi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MezunBilgiSistemi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210602230002_tarihli")]
    partial class tarihli
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MezunBilgiSistemi.Models.Duyurular", b =>
                {
                    b.Property<int>("DuyuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DuyuruAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuyuruAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuyuruFotoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("DuyuruId");

                    b.ToTable("Duyurulars");
                });

            modelBuilder.Entity("MezunBilgiSistemi.Models.Etkinlikler", b =>
                {
                    b.Property<int>("EtkinlikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EtkinlikAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtkinlikAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtkinlikFotoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("EtkinlikId");

                    b.ToTable("Etkinliklers");
                });

            modelBuilder.Entity("MezunBilgiSistemi.Models.Haberler", b =>
                {
                    b.Property<int>("HaberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HaberAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaberAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaberFotoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("HaberID");

                    b.ToTable("Haberlers");
                });
#pragma warning restore 612, 618
        }
    }
}
